name: Check and fix

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

concurrency: check-and-fix

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Check
        run: python3 -u checks.py
      - name: Fix
        run: python3 -u fixes.py
      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automatic fixes by fixes.py'
