name: Check and fix

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

concurrency: check-and-fix

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Set up Git config
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Cherry pick with fixes
        run: python3 -u cherry_pick_with_fixes.py
      - name: Check
        run: python3 -u checks.py
      - name: Commit and push fixes
        run: |
          git add .
          git diff-index --quiet --cached HEAD || git commit -m "Automatic fixes by cherry_pick_with_fixes.py"
          git push
